fun main () {
    val visitor0 = Besucher("Seb", 15)
    val visitor1 = Besucher("Boris", 4)

    val sheep0 = Schaf("Shawn", 23.4, 5, "weiblich")
    val sheep1 = Schaf("Peter", 30.4, 6, "männlich")
    val hen0 = Huhn("Siegrid", 2.5, 2, "weiblich", 2)
    val hen1 = Huhn("Sigi", 3.5, 2, "männlich", 0)
    val cow0 = Kuh("Berta", 525.0, 7, "weiblich", true)
    val cow1 = Kuh("Friedhelm", 600.0, 5, "männlich", false)
    val pony0 = Pony("Gustav", 315.0, 3, "männlich", 30.5)
    val pony1 = Pony("Sabine", 299.7, 3, "weiblich", 32.1)

    val streichelzoo = Streichelzoo(mutableListOf(sheep0, sheep1, hen0, hen1, cow0, cow1, pony0, pony1))

    println("\n1. Zunächst stellen sich die beiden Besucher vor.")
    visitor0.introduction()
    visitor1.introduction()
    println("\n2. Daraufhin macht eins der Hühner ein Geräusch.")
    hen1.animalNoises()
    println("\n3. Seb füttert das Schaf.")
    sheep0.feed(visitor0.name)
    println("\n4. Boris will auf einem der Ponys reiten.")
    pony1.riding(visitor1)
    println("\n5. Eines der Hühner läuft durchs Gehege.")
    hen0.move()
    println("\n6. Seb streichelt eins der Ponys.")
    pony0.petting(visitor0)
    println("\n7. Danach reitet Seb auf dem Pony.")
    pony0.riding(visitor0)
    println("\n8. Jetzt versucht Boris auf dem Pony zu reiten.")
    pony0.riding(visitor1)
    println("\n9. Boris versucht die Kuh zu melken.")
    cow1.milking(visitor0.name)
    println("\n10. Alle Tiere machen zusammen ihre Geräusche.\n")
    streichelzoo.allAnimalNoises()
    println("\n11. Fütterungszeit. Boris füttert alle Tiere.")
    streichelzoo.feedAllAnimals(visitor1.name)
    println("\n12. Zuletzt haben die beiden Ponys ein Rennen.")
    streichelzoo.ponyRace(pony0, pony1)
}